{{- if .Values.governance.auditor.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helpdesk.fullname" . }}-auditor
  labels:
    {{- include "helpdesk.labels" . | nindent 4 }}
    app.kubernetes.io/component: auditor
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: auditor
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: auditor
    spec:
      containers:
        - name: auditor
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/local/bin/auditor"]
          args:
            {{- if .Values.governance.auditd.persistence.enabled }}
            - "-socket=/data/audit/audit.sock"
            {{- else }}
            - "-audit-service=http://{{ include "helpdesk.fullname" . }}-auditd:{{ .Values.governance.auditd.port }}"
            {{- end }}
            {{- if .Values.governance.auditor.alertWebhook }}
            - "-webhook={{ .Values.governance.auditor.alertWebhook }}"
            {{- end }}
            {{- if .Values.governance.email.enabled }}
            - "-smtp-host={{ .Values.governance.email.smtpHost }}"
            - "-smtp-port={{ .Values.governance.email.smtpPort }}"
            - "-email-from={{ .Values.governance.email.from }}"
            - "-email-to={{ .Values.governance.email.to }}"
            {{- end }}
          env:
            {{- if and .Values.governance.email.enabled .Values.governance.email.smtpSecret }}
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.governance.email.smtpSecret }}
                  key: username
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.governance.email.smtpSecret }}
                  key: password
            {{- end }}
          {{- if .Values.governance.auditd.persistence.enabled }}
          volumeMounts:
            - name: audit-data
              mountPath: /data/audit
              readOnly: true
          {{- end }}
      {{- if .Values.governance.auditd.persistence.enabled }}
      volumes:
        - name: audit-data
          persistentVolumeClaim:
            claimName: {{ include "helpdesk.fullname" . }}-auditd
      {{- end }}
      restartPolicy: Always
{{- end }}
