apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: helpdesk-test
data:
  postgresql.conf: |
    listen_addresses = '*'
    max_connections = 20
    shared_buffers = 32MB
    log_statement = 'all'
  pg_hba.conf: |
    # TYPE  DATABASE  USER  ADDRESS     METHOD
    local   all       all               trust
    host    all       all   0.0.0.0/0   md5
    host    all       all   ::/0        md5
